layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

topics:
  - name: Data manipulation
    image_url: /images/seaborn.png

  - name: Algorithms
    image_url: /images/algs.jpg

  - name: Python
    image_url: /images/python.png
