title: Karol Latos
description:
  Software Engineer
  <br><br>
  Positively-minded and fast-learning Computer Science student in final year, eager to implement good practice in code and acquire new skills under the guidance of experienced co-workers. Clear understanding of the theory surrounding computer science, probability and statistics, optimization and decision making, artificial intelligence and more. Skills in Python and C++, as well as occasional C# and SQL. Expanding knowledge and growing is a crucial aspect of my life.
  <br><br>
  
theme: jekyll-theme-minimal
