layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  portfolio:
    - mps_course_grades
    - sorting_algorithms
    - schedule_creator
    - ant_system
    - evolution_strategy
    - Poker
    - MemoryConsoleGame
    - TextFightModule
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:

topics:
  - name: Python ecosystem
    image_url: /images/python.png

  - name: Data manipulation
    image_url: /images/seaborn.png

  - name: Machine learning
    image_url: /images/machine-learning.jpg
