layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: false
    projects: ["TourismCompanyApp" "4chan_scrapper" "bfck_interpreter" "TaskList" "FightSimulator" "FightModuleTAC" "AnagramFinder" "ExceptionsPresentationCode" "OaDM-O_1" "Templates" "PiSquare" "OaDM-Gn" "Interpolation" "Horner" "NumericalDifferentiation" "CommunicationAndSocialMedia" "ApproxOdeSolvingReport" "asm_bubble_sort" "asm_sqrt_newton" "gate_control_system" "rol-x.github.io"]

topics:
  - name: Python ecosystem
    image_url: /images/python.png

  - name: Data manipulation
    image_url: /images/seaborn.png

  - name: Machine learning
    image_url: /images/machine-learning.jpg

